In [1]:
import pandas as pd
import requests
import json

In [26]:
loc = r'.\stats\player\\'
player = '201939'
season = '2021-22'
file_name = 'scurry_' + season + '_off_stats'

**Request data from NBA API**

Set player id and season to get specific stats

In [27]:
headers = {
    'Accept': 'application/json, text/plain, */*',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://www.nba.com/'
}

r = requests.get('https://stats.nba.com/stats/leagueseasonmatchups?DateFrom=&DateTo=&LeagueID=00&OffPlayerID=' + player + '&Outcome=&PORound=0&PerMode=Totals&Season=' + season + '&SeasonType=Regular+Season', headers=headers, timeout=10)

**Convert to pandas dataframe**

Converts the raw json to a pandas dataframe to either export as a csv file, or to use in program

In [28]:
r_dict = json.loads(r.content)

data = r_dict['resultSets'][0]['rowSet']
columns = r_dict['resultSets'][0]['headers']

df = pd.DataFrame(data=data, columns=columns)
df

,SEASON_ID,OFF_PLAYER_ID,OFF_PLAYER_NAME,DEF_PLAYER_ID,DEF_PLAYER_NAME,GP,MATCHUP_MIN,PARTIAL_POSS,PLAYER_PTS,TEAM_PTS,...,MATCHUP_FG3A,MATCHUP_FG3_PCT,HELP_BLK,HELP_FGM,HELP_FGA,HELP_FG_PERC,MATCHUP_FTM,MATCHUP_FTA,SFL,MATCHUP_TIME_SEC
0,22021,201939,Stephen Curry,1629652,Luguentz Dort,2,16:32,87.2,21,103,...,9,0.556,0,0,0,0,2,2,1,992.4
1,22021,201939,Stephen Curry,1628969,Mikal Bridges,3,17:20,83.9,4,57,...,5,0.000,0,0,0,0,0,0,0,1039.5
2,22021,201939,Stephen Curry,1629680,Matisse Thybulle,2,15:03,82.3,15,94,...,15,0.133,0,0,0,0,3,4,2,903.0
3,22021,201939,Stephen Curry,1629645,Kevin Porter Jr.,3,16:11,81.4,17,63,...,8,0.375,0,0,0,0,2,3,1,970.8
4,22021,201939,Stephen Curry,1628366,Lonzo Ball,2,11:45,58.6,25,72,...,12,0.417,0,0,0,0,0,0,0,704.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,22021,201939,Stephen Curry,1629646,Charles Bassey,1,0:05,0.3,0,3,...,0,0.000,0,0,0,0,0,0,0,4.8
306,22021,201939,Stephen Curry,1630625,Dalano Banton,1,0:04,0.3,0,3,...,0,0.000,0,0,0,0,0,0,0,4.1
307,22021,201939,Stephen Curry,203918,Rodney Hood,1,0:03,0.2,0,0,...,0,0.000,0,0,0,0,0,0,0,3.0
308,22021,201939,Stephen Curry,1626195,Willy Hernangomez,1,0:02,0.1,0,0,...,0,0.000,0,0,0,0,0,0,0,1.7
309,22021,201939,Stephen Curry,1630194,Paul Reed,1,0:02,0.1,0,0,...,0,0.000,0,0,0,0,0,0,0,1.6

**Export as .csv**

Run to export as a csv file

In [29]:
df.to_csv(loc + file_name + '.csv', index=False)